### ISSUE TITLE
Question about task query sidebar

### ISSUE THREAD

**Issue by hacker-jerry** [YU000jp/Logseq-column-Layout#2]
👋Hi, thank you for writing this plugin! I have a question about how to automatically display my various task information in the right sidebar, such as TODO, DOING, DONE and so on?
After installing the plugin, the sidebar is blank with no information. Can you record a video to teach me how to set it up? Thanks!

**Comment by YU000jp** [comment]
I made a capture video today. https://github.com/YU000jp/Logseq-default-queries-journals/blob/main/README.md

On Logseq, edit config.edn file.
Once you've done that, create your own task and try it out.

**Comment by hacker-jerry** [comment]
Thx a lot!
