### ISSUE TITLE
date picker cover texts

### ISSUE THREAD

**Issue by TatamoChang** [YU000jp/Logseq-column-Layout#4]
when I create a task with sub contents, the contents will be covered by date picker
![image](https://user-images.githubusercontent.com/5977351/209439981-def043fc-166b-4d9b-bc6b-3e28a12a5ca4.png)

**Comment by YU000jp** [comment]
I'm going to try to troubleshoot.

Just in case, let me know which theme package you have selected.

**Comment by TatamoChang** [comment]
I use Discord Dark
![image](https://user-images.githubusercontent.com/5977351/209441995-9813b9f2-79a2-4e17-9e79-201ddf07d8f1.png)

**Comment by YU000jp** [comment]
Thanks to your help, I found the same situation.
Please update to new release.

**Comment by TatamoChang** [comment]
Works fine. Thank you.
